In [4]:
import numpy as np

In [58]:
def jacobi(u, eps=1):
    x = u.copy()
    y = u.copy()
    
    delt = eps + 1.0
    while delt > eps:
        for i in range(1, u.shape[0]-1):
            for j in range(1, u.shape[1]-1):
                y[i,j] = (x[i-1,j] + x[i+1,j] + x[i,j-1] + x[i,j+1]) / 4.0
        delt = np.sum( np. abs(x - y) )
        x, y = y, x     # Double buffering concept, short hand in python for doing swaps
        
    return x

In [59]:
u = np.zeros((10,10))
u

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [64]:
u[0,:]=100
u

array([[ 100.,  100.,  100.,  100.,  100.,  100.,  100.,  100.,  100.,
         100.],
       [   0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
           0.],
       [   0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
           0.],
       [   0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
           0.],
       [   0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
           0.],
       [   0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
           0.],
       [   0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
           0.],
       [   0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
           0.],
       [   0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
           0.],
       [   0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
           0.]])

In [65]:
v = jacobi(u)

In [52]:
import matplotlib.pyplot as plt

In [66]:
v

array([[ 100.        ,  100.        ,  100.        ,  100.        ,
         100.        ,  100.        ,  100.        ,  100.        ,
         100.        ,  100.        ],
       [   0.        ,   48.57288888,   66.80811301,   74.33326246,
          77.18440746,   77.18440746,   74.33326246,   66.80811301,
          48.57288888,    0.        ],
       [   0.        ,   27.49702316,   44.35182963,   53.3749187 ,
          57.2590695 ,   57.2590695 ,   53.3749187 ,   44.35182963,
          27.49702316,    0.        ],
       [   0.        ,   17.08888663,   29.77520076,   37.62010943,
          41.29133197,   41.29133197,   37.62010943,   29.77520076,
          17.08888663,    0.        ],
       [   0.        ,   11.11765191,   20.10450983,   26.12591619,
          29.09367876,   29.09367876,   26.12591619,   20.10450983,
          11.11765191,    0.        ],
       [   0.        ,    7.31620969,   13.47254725,   17.78410874,
          19.97606344,   19.97606344,   17.78410874,   13